<?php

namespace Database\Seeders;

use App\Models\Patient;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $jsondata='[
            {
                "PatientID": "89689",
                "FirstName": "Ben",
                "LastName": "Dover",
                "DateOfBirth": "16.12.1947",
                "WeightKG": "74",
                "GP_FirstName": "Shah",
                "GP_LastName": "Min´Azadeq",
                "Diagnosis_1": "Diabetes Mellitus",
                "MonitoredCondition1": "Blood oxygenation",
                "MonitoredCondition2": "Cough",
                "MonitoredCondition3": "Hypertension",
                "Meds1_Name": "Melyd 60x2 mg",
                "Meds1_Use_XperDay": "1",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "Diabetes"
            },
            {
                "PatientID": "1209",
                "FirstName": "George",
                "LastName": "Winker",
                "DateOfBirth": "1.2.1954",
                "WeightKG": "91",
                "GP_FirstName": "Shah",
                "GP_LastName": "Min´Azadeq",
                "Diagnosis_1": "Arthritis",
                "MonitoredCondition1": "Hypertension",
                "MonitoredCondition2": "Blood oxygenation",
                "MonitoredCondition3": "Cough",
                "Meds1_Name": "Tensiomin 30x25 mg",
                "Meds1_Use_XperDay": "2",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "High blood pressure"
            },
            {
                "PatientID": "1272",
                "FirstName": "Brigitte",
                "LastName": "Jones",
                "DateOfBirth": "7.12.1952",
                "WeightKG": "99",
                "GP_FirstName": "Shah",
                "GP_LastName": "Min´Azadeq",
                "Diagnosis_1": "Hypertension",
                "MonitoredCondition1": "Incontinence",
                "MonitoredCondition2": "Hypertension",
                "MonitoredCondition3": "Blood oxygenation",
                "Meds1_Name": "Tensiomin 30x25 mg",
                "Meds1_Use_XperDay": "3",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "High blood pressure"
            },
            {
                "PatientID": "2763",
                "FirstName": "Daniel",
                "LastName": "LaFette",
                "DateOfBirth": "22.4.1951",
                "WeightKG": "94",
                "GP_FirstName": "Shah",
                "GP_LastName": "Min`Azadeq",
                "Diagnosis_1": "Alzheimer`s disease",
                "MonitoredCondition1": "Nausea",
                "MonitoredCondition2": "Incontinence",
                "MonitoredCondition3": "Hypertension",
                "Meds1_Name": "Tensiomin 30x25 mg",
                "Meds1_Use_XperDay": "2",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "High blood pressure"
            },
            {
                "PatientID": "2873",
                "FirstName": "Leroy",
                "LastName": "Kentchuck",
                "DateOfBirth": "19.9.1954",
                "WeightKG": "103",
                "GP_FirstName": "Shah",
                "GP_LastName": "Min´Azadeq",
                "Diagnosis_1": "Osteoporosis",
                "MonitoredCondition1": "Join pain",
                "MonitoredCondition2": "Nausea",
                "MonitoredCondition3": "Incontinence",
                "Meds1_Name": "Norifaz 12x35 mg",
                "Meds1_Use_XperDay": "0.1428",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "Osteoporosis"
            },
            {
                "PatientID": "3092",
                "FirstName": "Nina",
                "LastName": "Chang",
                "DateOfBirth": "8.11.1953",
                "WeightKG": "74",
                "GP_FirstName": "Shah",
                "GP_LastName": "Min´Azadeq",
                "Diagnosis_1": "High cholesterol",
                "MonitoredCondition1": "Lower-back pain",
                "MonitoredCondition2": "Join pain",
                "MonitoredCondition3": "Nausea",
                "Meds1_Name": "Adezop 28x10 mg",
                "Meds1_Use_XperDay": "1",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "High cholesterol"
            },
            {
                "PatientID": "3628",
                "FirstName": "Nasta",
                "LastName": "Gregorhill",
                "DateOfBirth": "4.1..1952",
                "WeightKG": "98",
                "GP_FirstName": "Shah",
                "GP_LastName": "Min´Azadeq",
                "Diagnosis_1": "Pneumonia",
                "MonitoredCondition1": "Insomnia",
                "MonitoredCondition2": "Lower-back pain",
                "MonitoredCondition3": "Join pain",
                "Meds1_Name": "Dorsiflex 30x200 mg",
                "Meds1_Use_XperDay": "3",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "Back pain"
            },
            {
                "PatientID": "3672",
                "FirstName": "Bryan",
                "LastName": "Stephans",
                "DateOfBirth": "5.13.1951",
                "WeightKG": "60",
                "GP_FirstName": "Shah",
                "GP_LastName": "Min´Azadeq",
                "Diagnosis_1": "Chronic kidney disease",
                "MonitoredCondition1": "Cough",
                "MonitoredCondition2": "Insomnia",
                "MonitoredCondition3": "Lower-back pain",
                "Meds1_Name": "Solmucol 20x200 mg",
                "Meds1_Use_XperDay": "3",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "Cough"
            },
            {
                "PatientID": "3787",
                "FirstName": "Kamala",
                "LastName": "Boldwood",
                "DateOfBirth": "29.3.1931",
                "WeightKG": "96",
                "GP_FirstName": "Shah",
                "GP_LastName": "Min´Azadeq",
                "Diagnosis_1": "Chronic Obstructive Pulmonary Disease",
                "MonitoredCondition1": "Hypotension",
                "MonitoredCondition2": "Cough",
                "MonitoredCondition3": "Insomnia",
                "Meds1_Name": "Tensiomin 30x25 mg",
                "Meds1_Use_XperDay": "2",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "High blood pressure"
            },
            {
                "PatientID": "3872",
                "FirstName": "Dover",
                "LastName": "Pristine",
                "DateOfBirth": "1.4.1932",
                "WeightKG": "61",
                "GP_FirstName": "Shah",
                "GP_LastName": "Min´Azadeq",
                "Diagnosis_1": "Diabetes Mellitus",
                "MonitoredCondition1": "Diarrhea",
                "MonitoredCondition2": "Hypotension",
                "MonitoredCondition3": "Cough",
                "Meds1_Name": "Melyd 60X2mg",
                "Meds1_Use_XperDay": "1",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "Diabetes"
            },
            {
                "PatientID": "3929",
                "FirstName": "Janine",
                "LastName": "Komer",
                "DateOfBirth": "8.9.1933",
                "WeightKG": "100",
                "GP_FirstName": "Matus",
                "GP_LastName": "Kostolany",
                "Diagnosis_1": "Arthritis",
                "MonitoredCondition1": "Blood oxygenation",
                "MonitoredCondition2": "Diarrhea",
                "MonitoredCondition3": "Hypotension",
                "Meds1_Name": "Tensiomin 30x25 mg",
                "Meds1_Use_XperDay": "3",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "High blood pressure"
            },
            {
                "PatientID": "4322",
                "FirstName": "Katherine",
                "LastName": "Stealthant",
                "DateOfBirth": "26.7.1934",
                "WeightKG": "74",
                "GP_FirstName": "Matus",
                "GP_LastName": "Kostolany",
                "Diagnosis_1": "Hypertension",
                "MonitoredCondition1": "Hypertension",
                "MonitoredCondition2": "Blood oxygenation",
                "MonitoredCondition3": "Diarrhea",
                "Meds1_Name": "Tensiomin 30x25 mg",
                "Meds1_Use_XperDay": "2",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "High blood pressure"
            },
            {
                "PatientID": "4739",
                "FirstName": "Howard",
                "LastName": "Brice",
                "DateOfBirth": "22.10.1935",
                "WeightKG": "81",
                "GP_FirstName": "Matus",
                "GP_LastName": "Kostolany",
                "Diagnosis_1": "Alzheimer`s disease",
                "MonitoredCondition1": "Incontinence",
                "MonitoredCondition2": "Hypertension",
                "MonitoredCondition3": "Blood oxygenation",
                "Meds1_Name": "Donepezil Mylan 28x5 mg",
                "Meds1_Use_XperDay": "1",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "Memory"
            },
            {
                "PatientID": "5273",
                "FirstName": "Julia",
                "LastName": "Wootherland",
                "DateOfBirth": "13.11.1936",
                "WeightKG": "117",
                "GP_FirstName": "Matus",
                "GP_LastName": "Kostolany",
                "Diagnosis_1": "Osteoporosis",
                "MonitoredCondition1": "Nausea",
                "MonitoredCondition2": "Incontinence",
                "MonitoredCondition3": "Hypertension",
                "Meds1_Name": "Tensiomin 30x25 mg",
                "Meds1_Use_XperDay": "2",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "High blood pressure"
            },
            {
                "PatientID": "5689",
                "FirstName": "David",
                "LastName": "Loughlin",
                "DateOfBirth": "10.10.1937",
                "WeightKG": "64",
                "GP_FirstName": "Matus",
                "GP_LastName": "Kostolany",
                "Diagnosis_1": "Dementia",
                "MonitoredCondition1": "Join pain",
                "MonitoredCondition2": "Nausea",
                "MonitoredCondition3": "Incontinence",
                "Meds1_Name": "Donepezil Mylan 28x5 mg",
                "Meds1_Use_XperDay": "1",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "Memory"
            },
            {
                "PatientID": "7152",
                "FirstName": "Tiana",
                "LastName": "Gemeroon",
                "DateOfBirth": "8.2.1938",
                "WeightKG": "66",
                "GP_FirstName": "Matus",
                "GP_LastName": "Kostolany",
                "Diagnosis_1": "Pneumonia",
                "MonitoredCondition1": "Lower-back pain",
                "MonitoredCondition2": "Join pain",
                "MonitoredCondition3": "Nausea",
                "Meds1_Name": "Dorsiflex 30x200 mg",
                "Meds1_Use_XperDay": "3",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "Back pain"
            },
            {
                "PatientID": "7298",
                "FirstName": "Willow",
                "LastName": "Quincy",
                "DateOfBirth": "15.5.1939",
                "WeightKG": "111",
                "GP_FirstName": "Matus",
                "GP_LastName": "Kostolany",
                "Diagnosis_1": "Chronic kidney disease",
                "MonitoredCondition1": "Insomnia",
                "MonitoredCondition2": "Lower-back pain",
                "MonitoredCondition3": "Join pain",
                "Meds1_Name": "Dorsiflex 30x200 mg",
                "Meds1_Use_XperDay": "3",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "Back pain"
            },
            {
                "PatientID": "7569",
                "FirstName": "Erick",
                "LastName": "Pleinart",
                "DateOfBirth": "8.3.1940",
                "WeightKG": "88",
                "GP_FirstName": "Lubica",
                "GP_LastName": "Bires",
                "Diagnosis_1": "Chronic Obstructive Pulmonary Disease",
                "MonitoredCondition1": "Cough",
                "MonitoredCondition2": "Insomnia",
                "MonitoredCondition3": "Lower-back pain",
                "Meds1_Name": "Dorsiflex 30x200 mg",
                "Meds1_Use_XperDay": "3",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "Back pain"
            },
            {
                "PatientID": "7638",
                "FirstName": "Roberta",
                "LastName": "Kosova",
                "DateOfBirth": "22.4.1941",
                "WeightKG": "91",
                "GP_FirstName": "Lubica",
                "GP_LastName": "Bires",
                "Diagnosis_1": "Pneumonia",
                "MonitoredCondition1": "Hypotension",
                "MonitoredCondition2": "Cough",
                "MonitoredCondition3": "Insomnia",
                "Meds1_Name": "Solmucol 20x200 mg",
                "Meds1_Use_XperDay": "3",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "Cough"
            },
            {
                "PatientID": "7692",
                "FirstName": "Anastasia",
                "LastName": "Elebrey",
                "DateOfBirth": "29.8.1942",
                "WeightKG": "110",
                "GP_FirstName": "Lubica",
                "GP_LastName": "Bires",
                "Diagnosis_1": "Chronic kidney disease",
                "MonitoredCondition1": "Diarrhea",
                "MonitoredCondition2": "Hypotension",
                "MonitoredCondition3": "Cough",
                "Meds1_Name": "Tensiomin 30x25 mg",
                "Meds1_Use_XperDay": "3",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "High blood pressure"
            },
            {
                "PatientID": "9282",
                "FirstName": "Peter",
                "LastName": "Colothey",
                "DateOfBirth": "3.11.1943",
                "WeightKG": "94",
                "GP_FirstName": "Lubica",
                "GP_LastName": "Bires",
                "Diagnosis_1": "Chronic Obstructive Pulmonary Disease",
                "MonitoredCondition1": "Blood oxygenation",
                "MonitoredCondition2": "Diarrhea",
                "MonitoredCondition3": "Hypotension",
                "Meds1_Name": "Tensiomin 30x25 mg",
                "Meds1_Use_XperDay": "2",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "High blood pressure"
            },
            {
                "PatientID": "9780",
                "FirstName": "Xenia",
                "LastName": "Babson",
                "DateOfBirth": "28.6.1944",
                "WeightKG": "103",
                "GP_FirstName": "Lubica",
                "GP_LastName": "Bires",
                "Diagnosis_1": "Hypertension",
                "MonitoredCondition1": "Hypertension",
                "MonitoredCondition2": "Blood oxygenation",
                "MonitoredCondition3": "Diarrhea",
                "Meds1_Name": "Reasec 20x2,5 mg",
                "Meds1_Use_XperDay": "3",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "Diarrhea"
            },
            {
                "PatientID": "9896",
                "FirstName": "Marry",
                "LastName": "Leinhart",
                "DateOfBirth": "27.2.1945",
                "WeightKG": "77",
                "GP_FirstName": "Lubica",
                "GP_LastName": "Bires",
                "Diagnosis_1": "Hypertension",
                "MonitoredCondition1": "Cough",
                "MonitoredCondition2": "Hypertension",
                "MonitoredCondition3": "Blood oxygenation",
                "Meds1_Name": "Solmucol 20x200 mg",
                "Meds1_Use_XperDay": "3",
                "Meds1_Use_DosePerUse": "1",
                "Meds1_Purpose": "Cough"
            }
        ]';
        $data=json_decode($jsondata,true);
        DB::table('patients')->truncate();
        foreach($data as $patient){
            Patient::create(['patient_id'=>$patient['PatientID'],'first_name'=>$patient['FirstName'],'last_name'=>$patient['LastName'],'phone_number'=>'+421949832707']);
        }
    }
}
